### ISSUE TITLE
这个代码实现好像全程都没有节点会通过ChangeRole()成为Candidate角色？

### ISSUE THREAD

**Issue by ATX735** [yanxiaoqi932/Raft-6.824#1]

**Comment by yanxiaoqi932** [comment]
感谢反馈，方便给一下相关的日志或者debug信息吗

**Comment by ATX735** [comment]
整个项目搜索不到ChangeRole(candidate)的使用，只有ChangeRole(leader)和ChangeRole(follower)，说明整个过程没有显式地把节点转换为Candidate的过程

**Comment by ATX735** [comment]
还有一个问题是：根据原论文，节点currentTerm的自增应在集群中的节点超时后进行。而代码中是在raftElection.go中的ChangeRole()函数中，等待当前节点成为leader后才自增currentTerm。


> 感谢反馈，方便给一下相关的日志或者debug信息吗

**Comment by yanxiaoqi932** [comment]
> 整个项目搜索不到ChangeRole(candidate)的使用，只有ChangeRole(leader)和ChangeRole(follower)，说明整个过程没有显式地把节点转换为Candidate的过程

是的，你可以重新看一下startElection方法，changeRole(candidate)这个过程是存在的，只是没有通过调用changeRole函数来实现：
![image](https://github.com/yanxiaoqi932/Raft-6.824/assets/55906038/bf0761f5-7497-4ab8-affb-28fba4bc3873)

**Comment by ATX735** [comment]
谢谢解答~

> > 还有一个问题是：根据原论文，节点currentTerm的自增应在集群中的节点超时后进行。而代码中是在raftElection.go中的ChangeRole()函数中，等待当前节点成为leader后才自增currentTerm。
> > > 感谢反馈，方便给一下相关的日志或者debug信息吗
> 
> 这一部分的话，我认为自增currentTerm在选举前和选举后没有区别，出于稳妥，我认为应当等待leader正式选举完成后才能让currentTerm自增，当然你也可以放在前面，我个人认为没有明显区别
